### PR TITLE
Update to 1.18

### PR DESCRIPTION
**Pull request by solonovamax**
Updates mod to 1.18

### CODE REVIEW

**Comment by vinays6** [comment]
Not sure if you know but it's already on 1.18. Check out https://github.com/DarkKronicle/AdvancedChatCore/wiki/Modules-List

**Comment by solonovamax** [comment]
Ah, I did not realize that.

In that case, this repo should definitely be archived with a link to the new one

**Comment by solonovamax** [comment]
Closing because it's already updated in a new repo

**Comment by DarkKronicle** [comment]
Sorry for the confusion!

**Comment by solonovamax** [comment]
By the way, @DarkKronicle, you can archive the repository in
Settings -> Options -> Danger Zone -> Archive this repository
image

**Comment by DarkKronicle** [comment]
Yeah about to

**Pull request closed without merging**
